version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg16_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      # Локальные, аккуратные настройки:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=256MB
      -c work_mem=16MB
      -c maintenance_work_mem=128MB
      -c effective_cache_size=1GB
      -c max_wal_size=2GB
      -c wal_compression=on
      -c autovacuum_naptime=30s
      -c autovacuum_vacuum_scale_factor=0.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
